/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2013-07-08 06:41:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;

public final class pending_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Display pending query</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#CDFFFF\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<pre>\r\n");
      out.write("\r\n");
      out.write("                                                                                                        <a href =\"LogoutController\">[Logout]</a>\r\n");
      out.write("\r\n");
      out.write("</pre>\r\n");
      out.write("    \r\n");
      out.write("                                                                                                       \r\n");

try {

String connectionURL = "jdbc:mysql://localhost:3306/call_centre_management";

Connection connection = null;

Statement statement = null;

ResultSet rs = null;

Class.forName("com.mysql.jdbc.Driver").newInstance();

connection = DriverManager.getConnection(connectionURL, "root", "");

statement = connection.createStatement();
String QueryString = "SELECT * from enquiry_details where query_status='notdone'";
rs = statement.executeQuery(QueryString);

      out.write("\r\n");
      out.write("<font color=\"blue\"><center><u><h2>Details of Unaswered Query </h2></u></center></font>\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" cellpadding=\"25\" border=\"1\" style=\"background-color: #ffffcc;\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th>query id</th>\r\n");
      out.write("<th>employee id</th>\r\n");
      out.write("<th>customer id</th>\r\n");
      out.write("<th>query</th>\r\n");
      out.write("<th>query solution</th>\r\n");
      out.write("<th>status</th>\r\n");
      out.write("<th>date of query</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

while (rs.next()) {

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(rs.getInt(1));
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getInt(2));
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getInt(3));
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getString(7));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 } 
      out.write('\r');
      out.write('\n');

rs.close();
statement.close();
connection.close();
} catch (Exception ex) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<font size=\"+3\" color=\"red\">\r\n");

out.println("Unable to connect to database.");
}

      out.write("\r\n");
      out.write("</font>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<form action=\"pendingquery.jsp\" method=\"get\" >\r\n");
      out.write("<button type=\"submit\"> Back</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
